### ISSUE TITLE
Error:user not found

### ISSUE THREAD

**Issue by jinugeojames** [chainHero/heroes-service#29]
when I run network I created this error pops up.

Unable to initialize the Fabric SDK: failed to create channel management client from Admin identity: failed to create resmgmt client due to context error: user not found

**Comment by hduwyj** [comment]
Have you solved this problem?

**Comment by jinugeojames** [comment]
No,actually I moved to node sdk.

**Comment by hduwyj** [comment]
I can run on ubuntu 16.04, but I want to run on win10 and I get that error.

**Comment by jinugeojames** [comment]
I think its related to some admin enrollment.

**Comment by fusionwarecorp** [comment]
@jinugeojames It needs to map over to the user specified in your config.yaml file. I had this same issue.

![selection_168](https://user-images.githubusercontent.com/47606745/52891060-9db68600-3145-11e9-9520-0831e0ed0ccd.png)
![selection_169](https://user-images.githubusercontent.com/47606745/52891061-9f804980-3145-11e9-8451-68c353e329ff.png)

**Comment by 0xbuidler** [comment]
@antitoine I think we can close this issue.

**Comment by csquan** [comment]
have it solved？

**Comment by afrancoc2000** [comment]
For me this has also been a difficult issue to solve, another thing that works is using the users yaml instead of the cryptoPath like this:

```
organizations:
  Org1:
    mspid: Org1MSP
    users:
      Admin:
        cert:
          path: organizations/org1/users/Admin@example.com/msp/signcerts/cert.pem
        key:
          path: organizations/org1/users/Admin@example.com/msp/keystore/key.pem
```

Then you can see if there's an issue with your certificates and is easier to map the user.
